name: jaspr_bloc
description: Jaspr components that make it easy to implement the BLoC (Business
  Logic Component) design pattern. Built to be used with the bloc state
  management package.
version: 0.0.1
repository: https://github.com/f-person/jaspr_bloc
issue_tracker: https://github.com/f-person/jaspr_bloc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  jaspr: ^0.1.5
  jaspr_provider: 
    git:
      url: https://github.com/Maksimka101/jaspr_provider.git

dev_dependencies:
  jaspr_test: ^0.1.0
