name: jaspr_bloc
description: Jaspr components that make it easy to implement the BLoC (Business
  Logic Component) design pattern. Built to be used with the bloc state
  management package.
version: 0.0.2
repository: https://github.com/f-person/jaspr_bloc
issue_tracker: https://github.com/f-person/jaspr_bloc

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  jaspr: ^0.16.3
  jaspr_provider: ^0.0.3

dev_dependencies:
  jaspr_test: ^0.16.3
